repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-json
  - id: check-yaml
  - id: check-byte-order-marker
  - id: check-executables-have-shebangs
- repo: https://github.com/openstack-dev/bashate
  rev: 2.1.0
  hooks:
  - id: bashate
    args: [ -i, E006 ]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.8.0.1
  hooks:
  - id: shellcheck
    exclude_types: [ zsh ]
