sudo: required

jobs:
  include:
    - name: "pre-commit"
      language: python
      python: 3.6
      install: pip install pre-commit
      script: pre-commit run --all-files

    - name: "docker build"
      language: minimal
      script: ./build.sh
